// components/svelte/PixuCompressor.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  import type { CompressionOptions, CompressionResult } from 'pixu';

  export let options: CompressionOptions = {};
  export let autoCompress: boolean = true;
  export let samples: { id: string; label: string; url: string; file: string }[] = [];

  const dispatch = createEventDispatcher<{
    compress: CompressionResult;
    error: Error;
    progress: number;
    source: { file: File; url: string };
  }>();

  let file: File | null = null;
  let loading: boolean = false;
  let progress: number = 0;
  let error: string | null = null;
  let result: CompressionResult | null = null;
  let originalUrl: string | null = null;
  let compressedUrl: string | null = null;
  let originalSize: number = 0;
  let originalDimensions: string = '';
  let fileInput: HTMLInputElement;
  let compressFn: any = null;

  onMount(async () => {
    try {
      const module = await import('pixu');
      compressFn = module.compress;
    } catch (err) {
      console.error('Failed to load pixu:', err);
    }
  });

  onDestroy(() => {
    if (originalUrl) {
      URL.revokeObjectURL(originalUrl);
    }
    if (compressedUrl) {
      URL.revokeObjectURL(compressedUrl);
    }
  });

  function triggerFileInput() {
    fileInput?.click();
  }

  async function handleFileChange(event: Event) {
    const target = event.target as HTMLInputElement;
    const selectedFile = target.files?.[0];
    if (selectedFile) {
      await processFile(selectedFile);
    }
  }

  function handleDragOver(event: DragEvent) {
    event.preventDefault();
  }

  async function handleDrop(event: DragEvent) {
    event.preventDefault();
    const droppedFile = event.dataTransfer?.files[0];
    if (droppedFile && droppedFile.type.startsWith('image/')) {
      await processFile(droppedFile);
    }
  }

  async function loadSample(sample: { id: string; label: string; url: string; file: string }) {
    const res = await fetch(sample.url);
    if (!res.ok) return;
    const blob = await res.blob();
    const file = new File([blob], sample.file, { type: blob.type || 'image/jpeg' });
    await processFile(file);
  }

  async function processFile(selectedFile: File) {
    loading = true;
    error = null;
    progress = 0;
    result = null;

    if (originalUrl) {
      URL.revokeObjectURL(originalUrl);
      originalUrl = null;
    }
    if (compressedUrl) {
      URL.revokeObjectURL(compressedUrl);
      compressedUrl = null;
    }

    try {
      const buffer = await selectedFile.arrayBuffer();
      const type = selectedFile.type || 'image/jpeg';
      const previewBlob = new Blob([buffer.slice(0)], { type });
      const appPreviewBlob = new Blob([buffer.slice(0)], { type });
      const fileForCompress = new File([buffer.slice(0)], selectedFile.name, {
        type,
        lastModified: selectedFile.lastModified,
      });

      file = fileForCompress;
      originalUrl = URL.createObjectURL(previewBlob);
      originalSize = fileForCompress.size;
      dispatch('source', {
        file: fileForCompress,
        url: URL.createObjectURL(appPreviewBlob),
      });

      if (!autoCompress) {
        loading = false;
        return;
      }

      if (!compressFn) {
        const module = await import('pixu');
        compressFn = module.compress;
      }

      const compressionResult = await compressFn(fileForCompress, {
        ...options,
        onProgress: (p: number) => {
          progress = p;
          dispatch('progress', p);
        },
      });

      result = compressionResult;
      compressedUrl = URL.createObjectURL(compressionResult.file);
      dispatch('compress', compressionResult);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Compression failed';
      error = errorMessage;
      dispatch('error', err instanceof Error ? err : new Error(errorMessage));
    } finally {
      loading = false;
    }
  }

  function downloadFile() {
    if (!result || !compressedUrl) return;
    
    const link = document.createElement('a');
    link.href = compressedUrl;
    link.download = `compressed-${file?.name || 'image'}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  function reset() {
    file = null;
    result = null;
    error = null;
    progress = 0;
    if (originalUrl) {
      URL.revokeObjectURL(originalUrl);
      originalUrl = null;
    }
    if (compressedUrl) {
      URL.revokeObjectURL(compressedUrl);
      compressedUrl = null;
    }
  }

  function formatBytes(bytes: number): string {
    if (!Number.isFinite(bytes) || bytes === 0) return '0 Bytes';
    const sign = bytes < 0 ? '-' : '';
    const abs = Math.abs(bytes);
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.min(sizes.length - 1, Math.floor(Math.log(abs) / Math.log(k)));
    return `${sign}${Math.round((abs / Math.pow(k, i)) * 100) / 100} ${sizes[i]}`;
  }
</script>

<div class="pixu-compressor">
  {#if !file}
    <div class="upload-area" on:click={triggerFileInput} on:dragover={handleDragOver} on:drop={handleDrop}>
      <input
        bind:this={fileInput}
        type="file"
        on:change={handleFileChange}
        accept="image/*"
        class="file-input"
        style="display: none;"
      />
      <div class="upload-content">
        <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
          <polyline points="17 8 12 3 7 8"></polyline>
          <line x1="12" y1="3" x2="12" y2="15"></line>
        </svg>
        <p class="upload-text">Click or drag image here to compress</p>
        <p class="upload-hint">Supports JPEG, PNG, WEBP, AVIF, PIXU</p>
      </div>
      {#if samples.length}
        <div class="sample-gallery" on:click|stopPropagation>
          <p class="sample-label">Or try a real sample</p>
          <div class="sample-grid">
            {#each samples as sample (sample.id)}
              <button type="button" class="sample-card" on:click={() => loadSample(sample)}>
                <img src={sample.url} alt={sample.label} loading="lazy" />
                <span>{sample.label}</span>
              </button>
            {/each}
          </div>
        </div>
      {/if}
    </div>
  {:else}
    <div class="compression-container">
      <div class="image-preview-section">
        <div class="image-preview">
          <h4>Original</h4>
          {#if originalUrl}
            <img src={originalUrl} alt="Original" />
          {/if}
          <div class="image-info">
            <span>{formatBytes(originalSize)}</span>
            <span>{originalDimensions}</span>
          </div>
        </div>
        {#if result}
          <div class="image-preview">
            <h4>Compressed</h4>
            {#if compressedUrl}
              <img src={compressedUrl} alt="Compressed" />
            {/if}
            <div class="image-info">
              <span>{formatBytes(result.compressedSize)}</span>
              <span>{result.width}x{result.height}</span>
            </div>
          </div>
        {/if}
      </div>

      {#if loading}
        <div class="progress-section">
          <progress value={progress} max={1} class="progress-bar"></progress>
          <p class="progress-text">Compressing... {Math.round(progress * 100)}%</p>
        </div>
      {/if}

      {#if result}
        <div class="result-section">
          <div class="stats-grid">
            <div class="stat-item">
              <span class="stat-label">Compression Ratio</span>
              <span class="stat-value">{(result.compressionRatio * 100).toFixed(1)}%</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Size Reduction</span>
              <span class="stat-value">{formatBytes(originalSize - result.compressedSize)}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Format</span>
              <span class="stat-value">{result.format}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Quality</span>
              <span class="stat-value">{result.metadata?.quality == null ? '—' : `${Math.round(result.metadata.quality * 100)}%`}</span>
            </div>
          </div>
          <div class="actions">
            <button on:click={downloadFile} class="btn btn-primary">Download Compressed</button>
            <button on:click={reset} class="btn btn-secondary">Compress Another</button>
          </div>
        </div>
      {/if}

      {#if error}
        <div class="error-section">
          <p class="error-message">{error}</p>
          <button on:click={reset} class="btn btn-secondary">Try Again</button>
        </div>
      {/if}
    </div>
  {/if}
</div>

<style>
  .pixu-compressor {
    width: 100%;
    max-width: 1200px;
    margin: 0 auto;
  }

  .upload-area {
    border: 2px dashed #e5e7eb;
    border-radius: 8px;
    padding: 3rem;
    text-align: center;
    cursor: pointer;
    transition: all 0.3s ease;
    background: #f9fafb;
  }

  .upload-area:hover {
    border-color: #3b82f6;
    background: #ffffff;
  }

  .upload-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  .upload-content svg {
    color: #6b7280;
  }

  .upload-text {
    font-size: 1.1rem;
    font-weight: 500;
    color: #111827;
    margin: 0;
  }

  .upload-hint {
    font-size: 0.9rem;
    color: #6b7280;
    margin: 0;
  }

  .sample-gallery {
    margin-top: 1.5rem;
    padding-top: 1.25rem;
    border-top: 1px solid rgba(123, 63, 239, 0.25);
  }

  .sample-label {
    margin: 0 0 0.75rem;
    font-size: 0.75rem;
    font-weight: 700;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: #8b95a8;
  }

  .sample-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
    gap: 0.65rem;
  }

  .sample-card {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
    padding: 0.35rem;
    border: 1px solid rgba(123, 63, 239, 0.25);
    border-radius: 10px;
    background: rgba(18, 24, 38, 0.6);
    cursor: pointer;
  }

  .sample-card img {
    width: 100%;
    aspect-ratio: 4 / 3;
    object-fit: cover;
    border-radius: 6px;
  }

  .sample-card span {
    font-size: 0.72rem;
    font-weight: 600;
    color: #eef2ff;
  }

  .compression-container {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .image-preview-section {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5rem;
  }

  .image-preview {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .image-preview h4 {
    margin: 0;
    font-size: 0.9rem;
    font-weight: 600;
    color: #111827;
  }

  .image-preview img {
    width: 100%;
    height: auto;
    border: 1px solid #e5e7eb;
    border-radius: 6px;
    max-height: 400px;
    object-fit: contain;
  }

  .image-info {
    display: flex;
    justify-content: space-between;
    font-size: 0.85rem;
    color: #6b7280;
  }

  .progress-section {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .progress-bar {
    width: 100%;
    height: 8px;
    border-radius: 4px;
  }

  .progress-text {
    text-align: center;
    font-size: 0.9rem;
    color: #6b7280;
    margin: 0;
  }

  .result-section {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 1rem;
    padding: 1rem;
    background: #f9fafb;
    border-radius: 6px;
  }

  .stat-item {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .stat-label {
    font-size: 0.85rem;
    color: #6b7280;
  }

  .stat-value {
    font-size: 1.1rem;
    font-weight: 600;
    color: #3b82f6;
  }

  .actions {
    display: flex;
    gap: 1rem;
    justify-content: center;
  }

  .btn {
    padding: 0.75rem 1.5rem;
    border: none;
    border-radius: 6px;
    font-size: 0.9rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .btn-primary {
    background: #3b82f6;
    color: white;
  }

  .btn-primary:hover {
    background: #2563eb;
  }

  .btn-secondary {
    background: #f9fafb;
    color: #111827;
    border: 1px solid #e5e7eb;
  }

  .btn-secondary:hover {
    background: #f3f4f6;
  }

  .error-section {
    padding: 1.5rem;
    background: #fee2e2;
    border: 1px solid #ef4444;
    border-radius: 6px;
    text-align: center;
  }

  .error-message {
    color: #dc2626;
    margin: 0 0 1rem 0;
  }

  @media (max-width: 768px) {
    .image-preview-section {
      grid-template-columns: 1fr;
    }
    
    .stats-grid {
      grid-template-columns: 1fr 1fr;
    }
    
    .actions {
      flex-direction: column;
    }
  }
</style>

// components/react/PixuCompressor.tsx
import React, { useState, useRef, useCallback, useEffect } from 'react';
import type { CompressionOptions, CompressionResult } from 'pixu';

interface SampleImageOption {
  id: string;
  label: string;
  url: string;
  file: string;
}

interface PixuCompressorProps {
  options?: CompressionOptions;
  autoCompress?: boolean;
  samples?: SampleImageOption[];
  onCompress?: (result: CompressionResult) => void;
  onError?: (error: Error) => void;
  onProgress?: (progress: number) => void;
  onSource?: (payload: { file: File; url: string }) => void;
}

const PixuCompressor: React.FC<PixuCompressorProps> = ({
  options = {},
  autoCompress = true,
  samples,
  onCompress,
  onError,
  onProgress,
  onSource,
}) => {
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<CompressionResult | null>(null);
  const [originalUrl, setOriginalUrl] = useState<string | null>(null);
  const [compressedUrl, setCompressedUrl] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const formatBytes = useCallback((bytes: number): string => {
    if (!Number.isFinite(bytes) || bytes === 0) return '0 Bytes';
    const sign = bytes < 0 ? '-' : '';
    const abs = Math.abs(bytes);
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.min(sizes.length - 1, Math.floor(Math.log(abs) / Math.log(k)));
    return `${sign}${Math.round((abs / Math.pow(k, i)) * 100) / 100} ${sizes[i]}`;
  }, []);

  const processFile = useCallback(async (selectedFile: File) => {
    setLoading(true);
    setError(null);
    setProgress(0);
    setResult(null);

    if (originalUrl) {
      URL.revokeObjectURL(originalUrl);
      setOriginalUrl(null);
    }
    if (compressedUrl) {
      URL.revokeObjectURL(compressedUrl);
      setCompressedUrl(null);
    }

    try {
      const buffer = await selectedFile.arrayBuffer();
      const type = selectedFile.type || 'image/jpeg';
      const previewBlob = new Blob([buffer.slice(0)], { type });
      const appPreviewBlob = new Blob([buffer.slice(0)], { type });
      const fileForCompress = new File([buffer.slice(0)], selectedFile.name, {
        type,
        lastModified: selectedFile.lastModified,
      });

      setFile(fileForCompress);
      setOriginalUrl(URL.createObjectURL(previewBlob));
      onSource?.({
        file: fileForCompress,
        url: URL.createObjectURL(appPreviewBlob),
      });

      if (!autoCompress) {
        setLoading(false);
        return;
      }

      const { compress } = await import('pixu');

      const compressionResult = await compress(fileForCompress, {
        ...options,
        onProgress: (p: number) => {
          setProgress(p);
          onProgress?.(p);
        },
      });

      setResult(compressionResult);
      setCompressedUrl(URL.createObjectURL(compressionResult.file));
      onCompress?.(compressionResult);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Compression failed';
      setError(errorMessage);
      onError?.(err instanceof Error ? err : new Error(errorMessage));
    } finally {
      setLoading(false);
    }
  }, [options, autoCompress, onCompress, onError, onProgress, onSource, originalUrl, compressedUrl]);

  const handleFileChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      processFile(selectedFile);
    }
  }, [processFile]);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    const droppedFile = e.dataTransfer?.files[0];
    if (droppedFile && droppedFile.type.startsWith('image/')) {
      processFile(droppedFile);
    }
  }, [processFile]);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
  }, []);

  const triggerFileInput = useCallback(() => {
    fileInputRef.current?.click();
  }, []);

  const loadSample = useCallback(async (sample: SampleImageOption) => {
    const res = await fetch(sample.url);
    if (!res.ok) return;
    const blob = await res.blob();
    const file = new File([blob], sample.file, { type: blob.type || 'image/jpeg' });
    await processFile(file);
  }, [processFile]);

  const downloadFile = useCallback(() => {
    if (!result || !compressedUrl) return;
    
    const link = document.createElement('a');
    link.href = compressedUrl;
    link.download = `compressed-${file?.name || 'image'}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [result, compressedUrl, file]);

  const reset = useCallback(() => {
    setFile(null);
    setResult(null);
    setError(null);
    setProgress(0);
    if (originalUrl) {
      URL.revokeObjectURL(originalUrl);
      setOriginalUrl(null);
    }
    if (compressedUrl) {
      URL.revokeObjectURL(compressedUrl);
      setCompressedUrl(null);
    }
  }, [originalUrl, compressedUrl]);

  useEffect(() => {
    return () => {
      if (originalUrl) {
        URL.revokeObjectURL(originalUrl);
      }
      if (compressedUrl) {
        URL.revokeObjectURL(compressedUrl);
      }
    };
  }, [originalUrl, compressedUrl]);

  const originalSize = file?.size || 0;
  const originalDimensions = originalUrl ? 'Loading...' : '';

  if (!file) {
    return (
      <div className="pixu-compressor">
        <div
          className="upload-area"
          onClick={triggerFileInput}
          onDragOver={handleDragOver}
          onDrop={handleDrop}
        >
          <input
            ref={fileInputRef}
            type="file"
            onChange={handleFileChange}
            accept="image/*"
            className="file-input"
            style={{ display: 'none' }}
          />
          <div className="upload-content">
            <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
              <polyline points="17 8 12 3 7 8"></polyline>
              <line x1="12" y1="3" x2="12" y2="15"></line>
            </svg>
            <p className="upload-text">Click or drag image here to compress</p>
            <p className="upload-hint">Supports JPEG, PNG, WEBP, AVIF, PIXU</p>
          </div>
          {samples?.length ? (
            <div className="sample-gallery" onClick={(e) => e.stopPropagation()}>
              <p className="sample-label">Or try a real sample</p>
              <div className="sample-grid">
                {samples.map((sample) => (
                  <button
                    key={sample.id}
                    type="button"
                    className="sample-card"
                    onClick={() => loadSample(sample)}
                  >
                    <img src={sample.url} alt={sample.label} loading="lazy" />
                    <span>{sample.label}</span>
                  </button>
                ))}
              </div>
            </div>
          ) : null}
        </div>
      </div>
    );
  }

  return (
    <div className="pixu-compressor">
      <div className="compression-container">
        <div className="image-preview-section">
          <div className="image-preview">
            <h4>Original</h4>
            {originalUrl && <img src={originalUrl} alt="Original" />}
            <div className="image-info">
              <span>{formatBytes(originalSize)}</span>
              <span>{originalDimensions}</span>
            </div>
          </div>
          {result && (
            <div className="image-preview">
              <h4>Compressed</h4>
              {compressedUrl && <img src={compressedUrl} alt="Compressed" />}
              <div className="image-info">
                <span>{formatBytes(result.compressedSize)}</span>
                <span>{result.width}x{result.height}</span>
              </div>
            </div>
          )}
        </div>

        {loading && (
          <div className="progress-section">
            <progress value={progress} max={1} className="progress-bar"></progress>
            <p className="progress-text">Compressing... {Math.round(progress * 100)}%</p>
          </div>
        )}

        {result && (
          <div className="result-section">
            <div className="stats-grid">
              <div className="stat-item">
                <span className="stat-label">Compression Ratio</span>
                <span className="stat-value">{(result.compressionRatio * 100).toFixed(1)}%</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Size Reduction</span>
                <span className="stat-value">{formatBytes(originalSize - result.compressedSize)}</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Format</span>
                <span className="stat-value">{result.format}</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Quality</span>
                <span className="stat-value">
                  {result.metadata?.quality == null
                    ? '—'
                    : `${Math.round(result.metadata.quality * 100)}%`}
                </span>
              </div>
            </div>
            <div className="actions">
              <button onClick={downloadFile} className="btn btn-primary">
                Download Compressed
              </button>
              <button onClick={reset} className="btn btn-secondary">
                Compress Another
              </button>
            </div>
          </div>
        )}

        {error && (
          <div className="error-section">
            <p className="error-message">{error}</p>
            <button onClick={reset} className="btn btn-secondary">
              Try Again
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default PixuCompressor;
